### PR TITLE
fix(rpc): Can't sign/verify with name before auction is closed.

### LINKED ISSUE #626: signmessage during REVEAL
Currently it's possible to signmessage during REVEAL while my bid is in the lead but higher lockups are still unrevealed.

like this (at least up to block 79215):
Name:      cmax
String:    Highest Lockup still not revealed
Signature: bmhWbed/6745rkwzJufRYhFvEi0iSLvbZAHT8zHr1dV+j7XLVa57soU2Po8Vtj/hHBGQA+CDf3WzbEneAAQfHA==

### PR DESCRIPTION
**Pull request by Falci**
Fix #626

### CODE REVIEW

File: lib/node/rpc.js [hunk 1]
```diff
@@ -2166,6 +2169,11 @@ class RPC extends RPCBase {
     if (!ns || !ns.owner)
       throw new RPCError(errs.MISC_ERROR, 'Cannot find the name owner.');
 
+    const state = ns.state(height, network);
+
+    if (state < states.CLOSED)
```
Comment (pinheadmz) [inline lib/node/rpc.js:2174]: Technically `REVOKED` is > `CLOSED`, any reason why this isn't `===` ?

Comment (Falci) [reply lib/node/rpc.js]: You're. It should throw error if `!== CLOSED`. Added an extra test and fixed.

**Comment by realrasengan** [comment]
This is great!

I had one question, since namestate exposes an `isClosed(height, network)`:
```
    return this.state(height, network) === states.CLOSED;
```
would it make sense to use that?  Sorry to be nitpicky -- but whatever we decide will probably also help to define the coding style go forward!

File: test/wallet-rpc-test.js [hunk 2]
```diff
@@ -466,6 +466,138 @@ describe('Wallet RPC Methods', function() {
     });
   });
 
+  describe('signmessagewithname & verifymessagewithname (reveal in progress)', () => {
```
Comment (pinheadmz) [inline test/wallet-rpc-test.js:469]: So I think these tests can the REVOKE tests can be combined into the existing `describe` block for simplicity. Change line 401 to mine 1 block only, then the first few `it` blocks can be the not-closed-yet tests. Then after line 466 you can mine more blocks and squeeze in the REVOKE test, so that `describe` block is all one long timeline.

**Review by pinheadmz — CHANGES_REQUESTED** [review]
In addition to merging the tests, I think all this PR can be squashed into one commit. We don't need extra "Lint" commits in the history ;-)
