### PR TITLE
Attach network default clearnet p2p port (and null ID key) to hosts received from DNS seeds.

### LINKED ISSUE #359: Issues using DNS seeds to bootstrap to the network
I may have executed this wrong, in which case we need some docs, or there might be 2 distinct bugs here. The goal was to use a DNS seeder (running `hs-seeder`) to discover peers and bootstrap to the network.

First try:
```
$  hsd --prefix=~/.hsd/dnsseed --seeds=seed.easyhandshake.com
...
[warning] (net) Could not find enough peers.
[warning] (net) Hitting DNS seeds...
[info] (hostlist) Resolving host: seed.easyhandshake.com.
AssertionError [ERR_ASSERTION]: Assertion failed.
    at HostList.add (/Users/matthewzipkin/Desktop/work/hsd/lib/net/hostlist.js:455:5)
    at HostList.populateSeed (/Users/matthewzipkin/Desktop/work/hsd/lib/net/hostlist.js:1050:12)
    at async Promise.all (index 0)
    at async Pool.discoverSeeds (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:589:7)
    at async Pool._connect (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:345:5)
    at async Pool.connect (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:323:14)
    at async /Users/matthewzipkin/Desktop/work/hsd/bin/node:69:3

```

That error is due to a missing port number:

https://github.com/handshake-org/hsd/blob/1c2d1036b262ecb767e71a73cd91ef11c940b230/lib/net/hostlist.js#L454-L455

So I tried adding a port number:

```
$ hsd --prefix=~/.hsd/dnsseed --seeds=seed.easyhandshake.com:53
...
[warning] (net) Could not find enough peers.
[warning] (net) Hitting DNS seeds...
[info] (hostlist) Resolving host: seed.easyhandshake.com.
[info] (net) Resolved 66 hosts from DNS seeds.
[debug] (net) Connecting to 96.250.207.28:53.
[info] (net) Adding loader peer (96.250.207.28:53).
[debug] (net) Connecting to 211.41.246.66:53.
[debug] (net) Connecting to [2601:341:c180:3a80:182e:dea3:a267:bb1e]:53.
[debug] (net) Connecting to 171.6.236.219:53.
[debug] (net) Connecting to 3.17.33.134:53.
[debug] (net) Connecting to [2604:2000:1403:459c:ca9:15d6:3acb:80be]:53.
[debug] (net) Connecting to [2001:0:2877:7aa:28af:57f2:4ad3:c359]:53.
[debug] (net) Connecting to [2a02:a31a:a146:c80:4:4faa:73cc:147b]:53.
[debug] (net) Error: Socket Error: EHOSTUNREACH 
[debug] (net) Connecting to [2a01:4b00:8069:6400:8f9:f6b7:bcb8:ebab]:53.
[debug] (net) Connecting to 95.165.154.226:53.
[debug] (net) Connecting to 64.203.198.140:53.
[debug] (net) Connecting to [2601:901:4380:1140:1063:17fe:4d37:3baa]:53.
[debug] (net) Error: Socket Error: EHOSTUNREACH ([2a01:4b00:8069:6400:8f9:f6b7:bcb8:ebab]:53)
...
```

Looks like it successfully retrieved the A/AAAA records from the seed node (can confirm on my server logs) but it's trying to connect to all the peers on port `53`!

ping @stp-ip

### PR DESCRIPTION
**Pull request by pinheadmz**
Closes #359 

Fixes two bugs. It's a bit weird since how we manage getting hosts from a DNS seed is by adding a port to the seed. We won't use that port (DNS lookup ignores that port, and does it's DNS thing on port 53 anyway) but it is inherited by all the hosts we receive from the DNS seed, which are otherwise just IP addresses in A/AAAA records.

There is also I think some leftover code from before the Brontide refactor, where we would attach the ID key of the DNS seed to all the hosts we received as A/AAAA records. I'm not sure how that was supposed to work, but it seems cleaner now to set the key to `null`.

This fix will have to be upgraded in the future if we switch to `SRV` records like in [BOLT-10](https://github.com/lightningnetwork/lightning-rfc/blob/master/10-dns-bootstrap.md) but for now, the DNS seeds are clearnet, legacy DNS resolvers that provide boring old fashioned A/AAAA records for peers without Brontide information.

to reproduce:

```
$ hsd --prefix=~/.hsd/dnsseed-test --seeds=seed.easyhandshake.com

...
[info] (node) Node is loaded.
[warning] (net) Could not find enough peers.
[warning] (net) Hitting DNS seeds...
[info] (hostlist) Resolving host: seed.easyhandshake.com.
[info] (net) Resolved 73 hosts from DNS seeds.
[debug] (net) Connecting to [2001:0:348b:fb58:c4d:3bfa:98a5:61f6]:12038.
[info] (net) Adding loader peer ([2001:0:348b:fb58:c4d:3bfa:98a5:61f6]:12038).
[debug] (net) Connecting to [2601:482:8002:2024:7531:8f8b:3508:1072]:12038.
[debug] (net) Connecting to 170.52.153.17:12038.
[debug] (net) Connecting to 64.227.51.86:12038.
[debug] (net) Connecting to 216.165.95.133:12038.
[debug] (net) Connecting to 24.201.194.199:12038.
[debug] (net) Connecting to [2601:341:c180:3a80:182e:dea3:a267:bb1e]:12038.
[debug] (net) Connecting to 95.165.154.226:12038.
[debug] (net) Error: Socket Error: EHOSTUNREACH ([2001:0:348b:fb58:c4d:3bfa:98a5:61f6]:12038)
[info] (net) Removed loader peer ([2001:0:348b:fb58:c4d:3bfa:98a5:61f6]:12038).
```

### CODE REVIEW

**Comment by stp-ip** [comment]
+1

File: lib/net/hostlist.js [hunk 1]
```diff
@@ -1072,10 +1078,10 @@ class HostList {
       return addrs;
     }
 
-    const {port, key} = target;
+    const {port} = target;
```
Comment (boymanjor) [inline lib/net/hostlist.js]: @pinheadmz do we need to use `target` here? Whether `target` is a node address or dns seed domain, I think we want to set the resultant `NetAddress`'s port to `this.network.defaultPort` and its key to `null`.

Comment (pinheadmz) [reply lib/net/hostlist.js]: Good point, I posted a commit (we can squash) that simplifies the process.

It's weird because we use the seeds list for both DNS seeds and actual peers. The latter require a custom port and a fallback port, but DNS seeds only ever use one port (53) and the results they return will always have no port (A/AAAA records) so we must add one.

Bcoin still runs this way: assigning the default network port to the DNS seed, and then the resolved records all inherit that port -- I'm not sure why that is still in place when we can simplify it like in https://github.com/handshake-org/hsd/pull/364/commits/296e89751fd6420bfffbca0abf8b9172f1b9aca7.

Then of course adding Brontide complicates it more which is why we ended up with the bug. If we ever set up something like BOLT-10 for Brontide peers, we may need to adjust this whole thing again, maybe even set up DNS seeds on a non-standard port.

**Comment by boymanjor** [comment]
@pinheadmz when you squash this we'll merge it.

**Comment by pinheadmz** [comment]
@boymanjor squashed!
